version: "3"

services:
  strapi:
    build: .
    restart: always
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-sqlite}
      DATABASE_HOST: ${DATABASE_HOST:-localhost}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
