# Use the official Strapi image
FROM strapi/strapi:3.6.8

# Expose Strapi default port
EXPOSE 1337

# Set working directory
WORKDIR /srv/app

# Copy package.json and yarn.lock to install dependencies
COPY package.json yarn.lock ./

# Install Strapi dependencies
RUN yarn install
